# --- !Ups

CREATE TABLE stations (Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(255) NOT NULL, Location VARCHAR(255), Password VARCHAR(255) NOT NULL);
CREATE TABLE bike_status (Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(255) NOT NULL);
CREATE TABLE bikes (Id VARCHAR(255) NOT NULL PRIMARY KEY,KeyBarcode VARCHAR(255),ReferenceId VARCHAR(255),LicensePlate VARCHAR(255),Remark VARCHAR(255), Detail VARCHAR(255),CreatedAt TIMESTAMP,UpdatedAt TIMESTAMP,StatusId INT,StationId INT);


# --- !Downs

DROP TABLE bikes
DROP TABLE bike_status
DROP TABLE stations